server:
  port: 8086

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/entity_db_service?allowPublicKeyRetrieval=true&useSSL=false&allowMultiQueries=true&serverTimezone=UTC
    username: dev
    password: 'Mul7899968@@@'
    driver-class-name: com.mysql.cj.jdbc.Driver

  ## Spring JPA
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:9000

      client:
        registration:
          master-data-service:
            client-id: entity-service-cli
            client-secret: secret
            authorization-grant-type: client_credentials
            scope: openid
            redirect-uri: https://oauthdebugger.com/debug
            provider: master-data-service

        provider:
          master-data-service:
            token-uri: http://localhost:9000/oauth2/token
            authorization-uri: http://localhost:9000/oauth2/authorize
            issuer-uri: http://localhost:9000

logging:
  level:
    root: INFO
    com.sysconnect.dev.erp_proyect: DEBUG
    org.springframework.security: DEBUG
    org.springframework.security.oauth2: DEBUG
    org.springframework.web.client.RestTemplate: DEBUG