server:
  port: 9000

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/authorization_db_service?allowPublicKeyRetrieval=true&useSSL=false&allowMultiQueries=true&serverTimezone=UTC
    username: dev
    password: 'Mul7899968@@@'
    driver-class-name: com.mysql.cj.jdbc.Driver

  ## Spring JPA
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update

loggin:
  level:
    com.sysconnect.dev.erp_proyect.master_data_service: DEBUG