server:
  port: 9000

auth:
  server:
    issuer-uri:  http://localhost:9000

spring:

  ## Base de datos
  datasource:
    url: jdbc:mysql://localhost:3306/authorization_db_service?allowPublicKeyRetrieval=true&useSSL=false&allowMultiQueries=true&serverTimezone=UTC
    username: dev
    password: 'Mul7899968@@@'
    driver-class-name: com.mysql.cj.jdbc.Driver

  ## Mail config
  mail:
    host: smtp.gmail.com
    port: 587
    username: sservex@gmail.com
    password: vxpvrjpmomawoddl
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

  ## Spring JPA
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update

loggin:
  level:
    com.sysconnect.dev.erp_proyect.master_data_service: DEBUG