server:
  port: 8085

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/masterdata_db_service?allowPublicKeyRetrieval=true&useSSL=false&allowMultiQueries=true&serverTimezone=UTC
    username: dev
    password: 'Mul7899968@@@'
    driver-class-name: com.mysql.cj.jdbc.Driver

  ## Spring JPA
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update


  ## Para feign client conexion con authentication service
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:9000

      client:
        registration:
          master-data-service:
            client-id: master-data-service-cli
            client-secret: secret
            authorization-grant-type: authorization_code
            scope: openid
            redirect-uri: https://oauthdebugger.com/debug

        provider:
          master-data-service:
            token-uri: http://localhost:9000/oauth2/token
            authorization-uri: http://localhost:9000/oauth2/authorize

loggin:
  level:
    com.sysconnect.dev.erp_proyect.master_data_service: DEBUG